#!/bin/bash

CFG_DIR=~/.config/FFF

check_config_dir () {
  if [ ! -d $CFG_DIR ]
  then
    echo "Configuration directory does not exist."
    echo "Creating and populating it with default values."
    mkdir -p ~/.config/FFF
    cp config/FFF $CFG_DIR
  fi
}

#check_whitespace () {
#  check_config_dir
#  if [ -f $CFG_DIR/whitespace.cfg ]
#  then
#    echo "Whitespace configuration file not present."
#    echo "Creating it with default values."
#    cp config/FFF/whitespace.cfg $CFG_DIR/whitespace.cfg
#  fi
#}

FFF () {

# Semicolon is used to separate searches
IFS=';'; WORDS=($(zenity --entry))

for WORD in "${WORDS[@]}"
do
  
  # substitute whitespace
  # plus sign + 
  WORD_PLUS=$(echo $WORD | sed 's/ /+/g')
  # minus sign -
  WORD_MINUS=$(echo $WORD | sed 's/ /-/g')
  # percent encoding %20
  WORD_PERC=$(echo $WORD | sed 's/ /%20/g')

  [ -z $WORD ] && exit ||
  xdg-open $AMAZON_DE$WORD_PLUS
  xdg-open $EBAY_DE$WORD_PLUS$EBAY_LOWEST_PRICE
  xdg-open $EBAY_DE$WORD_PLUS$EBAY_END_SOONEST$EBAY_AUCTION
  xdg-open $EBAY_KL$WORD_MINUS/k0
  xdg-open $MEDIMOPS$WORD_PLUS
  xdg-open $REBUY$WORD_PERC$REBUY_LOWEST_PRICE
  xdg-open $WOB$WORD_PERC

  sleep 1

done

}
