#!/bin/bash

source $CFG_DIR/books.cfg

echo "Searching category: books"

xdg-open $AMAZON_DE$WORD_PLUS
xdg-open $EBAY_DE$WORD_PLUS$EBAY_LOWEST_PRICE
xdg-open $EBAY_DE$WORD_PLUS$EBAY_END_SOONEST$EBAY_AUCTION
xdg-open $MEDIMOPS$WORD_PLUS$MEDIMOPS_LOWEST_PRICE
xdg-open $REBUY$WORD_PERC$REBUY_LOWEST_PRICE
xdg-open $WOB$WORD_PERC
